language: java
install: true
jobs:
  include:

  - stage: check
    install: true
    script: ./gradlew check
    after_success: |
      ./gradlew jacocoTestReport sonarqube \
          -Dsonar.projectKey=$SONAR_PROJECT_KEY \
          -Dsonar.organization=$SONAR_ORGANISATION \
          -Dsonar.host.url=$SONAR_HOST_URL \
          -Dsonar.login=$SONAR_LOGIN \
          || exit $?
      bash <(curl -s https://codecov.io/bash)

  - stage: checkDeploy
    if: "(type != push) AND (branch = master)"
    script: |
      GH_PROJECT_PATH=${TRAVIS_REPO_SLUG} ./gradlew -m release || exit $?
      REPO_URL=$(git remot get-url origin) || exit $?
      git push -n --tags https://${GITHUB_TOKEN}:x-oauth-basic@${REPO_URL#https://} || exit $?

  - stage: deploy
    if: "(type = push) AND (branch = master)"
    script: |
      GH_PROJECT_PATH=${TRAVIS_REPO_SLUG} ./gradlew release || exit $?
      REPO_URL=$(git remot get-url origin) || exit $?
      git push --tags https://${GITHUB_TOKEN}:x-oauth-basic@${REPO_URL#https://} || exit $?
    deploy:
      provider: releases
      api_key: ${GITHUB_TOKEN}
      file_glob: true
      file: build/libs/*
      skip_cleanup: true
      on:
        tags: true

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/modules-2/"
  - "$HOME/.gradle/wrapper/"

